/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: ["./app/**/*.{js,jsx}", "./components/**/*.{js,jsx}", "./preview.js"],
  theme: {
    extend: {
      colors: {
        "surface-dim": "#131313",
        "on-primary-fixed": "#221b00",
        "surface-container-lowest": "#0e0e0e",
        "on-secondary-fixed-variant": "#454747",
        "surface-container-high": "#2a2a2a",
        secondary: "#c6c6c7",
        "outline-variant": "#4c4734",
        "tertiary-fixed": "#9fefff",
        "inverse-primary": "#6f5d00",
        "surface-tint": "#e4c538",
        "on-secondary-container": "#b4b5b5",
        "on-primary": "#3a3000",
        "on-error": "#690005",
        "on-tertiary": "#00363e",
        "inverse-on-surface": "#313030",
        "on-tertiary-fixed": "#001f24",
        outline: "#98907a",
        "surface-container-low": "#1c1b1b",
        "on-primary-fixed-variant": "#544600",
        primary: "#fff2cc",
        "primary-fixed-dim": "#e4c538",
        surface: "#131313",
        "tertiary-container": "#63e8ff",
        "on-surface": "#e5e2e1",
        "secondary-container": "#454747",
        "on-error-container": "#ffdad6",
        "on-primary-container": "#6d5c00",
        "surface-container": "#201f1f",
        "on-secondary-fixed": "#1a1c1c",
        "inverse-surface": "#e5e2e1",
        "secondary-fixed-dim": "#c6c6c7",
        "primary-container": "#f5d547",
        "on-background": "#e5e2e1",
        "surface-bright": "#3a3939",
        error: "#ffb4ab",
        "surface-variant": "#353534",
        "primary-fixed": "#ffe166",
        "on-tertiary-container": "#006774",
        tertiary: "#daf8ff",
        "secondary-fixed": "#e2e2e2",
        "error-container": "#93000a",
        "tertiary-fixed-dim": "#4fd7ee",
        "on-tertiary-fixed-variant": "#004e59",
        "on-surface-variant": "#cfc6ae",
        background: "#0A0A0A",
        "surface-container-highest": "#353534",
        "on-secondary": "#2f3131",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "container-max": "1440px",
        "margin-mobile": "16px",
        "margin-desktop": "48px",
        gutter: "24px",
        base: "8px",
      },
      fontFamily: {
        "headline-xl": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "label-caps": ["Inter", "sans-serif"],
      },
      fontSize: {
        "headline-xl": ["48px", { lineHeight: "1.1", letterSpacing: "-0.04em", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "1.3", letterSpacing: "-0.02em", fontWeight: "600" }],
        "body-sm": ["14px", { lineHeight: "1.5", letterSpacing: "0em", fontWeight: "400" }],
        "headline-lg-mobile": ["28px", { lineHeight: "1.2", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "1.6", letterSpacing: "0em", fontWeight: "400" }],
        "headline-lg": ["32px", { lineHeight: "1.2", letterSpacing: "-0.03em", fontWeight: "700" }],
        "label-caps": ["12px", { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
};
